{
 "title": "Page Load Time Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "5-Minute Probe Duration History",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(probe_duration_seconds[5m])",
     "legendFormat": "5 min avg"
    }
   ]
  },
  {
   "title": "15-Minute Probe Duration History",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(probe_duration_seconds[15m])",
     "legendFormat": "15 min avg"
    }
   ]
  },
  {
   "title": "10-Minute Probe Duration History",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(probe_duration_seconds[10m])",
     "legendFormat": "10 min avg"
    }
   ]
  },
  {
   "title": "Current Probe Duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 19 },
   "format": "s",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "probe_duration_seconds" }
   ]
  }
 ]
}