{
 "title": "Online Status Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Page Online",
   "type": "table",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "probe_success " },
    {
     "expr": "avg_over_time(probe_success[5m])"
    },
    {
     "expr": "avg_over_time(probe_success[10m])"
    },
    {
     "expr": "avg_over_time(probe_success[15m])"
    }
   ]
  },
  {
   "title": "Weekly Online Status History",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "avg_over_time(probe_success[7d])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Monthly Online Status History",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "avg_over_time(probe_success[30d])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Yearly Online Status History",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "avg_over_time(probe_success[365d])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}