global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'network-exporter'
    static_configs:
      - targets: ['your ip:9101']

  - job_name: 'user-exporter'
    static_configs:
      - targets: ['your ip:9102']

  - job_name: 'hardware-exporter'
    static_configs:
      - targets: ['your ip:9103']

  - job_name: 'process-exporter'
    static_configs:
      - targets: ['your ip:9104']
  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']
  - job_name: 'website-monitoring'
    static_configs:
      - targets: ['your ip:9106']

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://gateway.nobicode.ir
        - https://google.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

